### ISSUE TITLE
csv export

### ISSUE THREAD

**Issue by luchomazze** [PBrunot/owonb41t#1]
Hi! Thank you for your efforts, PBrunot. 
Is it possible to obtain a .csv file containing the data presented in the chart?

**Comment by PBrunot** [comment]
Hi luchomazze, what is your use case exactly ? 
Right now the latest 75 samples are in the javascript array chartData[] (used for plotting). This array is reset on meter function change. Would exporting these samples good enough for you ?

**Comment by PBrunot** [comment]
Stale.
Not planning to implement at the moment.
Please reopen or vote for the issue if you have any interest in it.
