### ISSUE TITLE
OBS Support

### ISSUE THREAD

**Issue by seimei** [PBrunot/owonb41t#2]
Hi, is there any way to implement the output to OBS? in OBS you can add a website but in this html it shows only the multimeter picture.

Thanks for your great website anyway!

**Comment by PBrunot** [comment]
Hello, please confirm my understanding : you would like the measurement from the meter to be shown in a more realistic manner (value on meter photo) so that you can grab the image in OBS?

**Comment by seimei** [comment]
Exactly what I mean. I ordered an USB [dongle ](https://eleshop.de/owon-usb-bluetooth-dongle.html) which should be used for owon products but I have a clone of the Owon MM, it's called Jabe 36B and it also works with this dongle.
This is the [software ](https://files.owon.com.cn/software/PC/PC_software_for_OWON_Blue_meter(win10%20win11%2064bits%20system).zip)they recommend to use. The dongle is a BLE to Serial converter as I found out which is using the TI CC2540 IC.
With the iMeter sofware they provide it's enough for OBS. Maybe you can/want to implement it anyways for some who don't have the dongle for it.

**Comment by PBrunot** [comment]
Thanks for the update.

I think I can add a 7-segment LED display look like this one :
https://youtu.be/JeOqtmoNIyk?si=QnIMv--Feo6ZQSuy&t=429

It's not looking like the original meter LCD display, but some content creator (e.g. Sorin from Electronics Repair) use similar looking display on their videos. It is important to keep the exact same look in your opinion ?

**Comment by PBrunot** [comment]
Added LCD style display and updated web demo site.
